return {
  ensure_installed = {
    'gopls',
    'templ',
    'rust_analyzer',
    'volar',
    'clangd',
    'omnisharp',
    'lua_ls',
    'html',
    'cssls',
    'tailwindcss',
    'vtsls',
  },
  lint_fmt = {
    "prettier",
    "rustywind",
    'rustfmt',
    'goimports',
    'gofumpt',
    "volar",
    "eslint_d",
    -- "cpplint"
  },
  fmt_by_language = {
    javascript = { 'prettier' },
    typescript = { 'prettier' },
    vue = { 'prettier' },
    tailwind = { 'rustywind' },
    css = { 'prettier' },
    html = { 'prettier' },
    json = { 'prettier' },
    yaml = { 'prettier' },
    markdown = { 'prettier' },
    lua = { 'stylua' },
    rust = { 'rustfmt' },
    go = { 'goimports', 'gofmt' },
    ['_'] = { 'trim_whitespace' },
  },
  linters_by_language = {
    javascript = { 'eslint_d' },
    typescript = { 'eslint_d' },
    javascriptreact = { 'eslint_d' },
    typescriptreact = { 'eslint_d' },
    vue = { 'volar', 'eslint_d' },
    -- cpp = { 'cpplint' },
  },
  server_configs = {
    vtsls = {},
    gopls = { filetypes = { 'go', 'templ' } },
    templ = { filetypes = { 'templ' } },
    rust_analyzer = { check = { command = 'clippy' } },
    volar = { filetypes = { 'vue' } },
    html = { filetypes = { 'html', 'templ' } },
    tailwindcss = { filetypes = { 'html', 'vue' } },
    clangd = { filetypes = { 'c', 'h', 'c++', 'cpp', 'hpp' }, capabilities = { offsetEncoding = 'utf-8' } },
    omnisharp = { filetypes = { 'cs', 'csharp', 'c#' } },

    lua_ls = {
      Lua = {
        workspace = { checkThirdParty = false },
        telemetry = { enable = false },
      },
    },
  },
}
